#!/usr/bin/env bash
# cme-dnssec-monitor/clean v0.1.0
# removes DS keys from bind

if [[ $# -lt 4 ]]; then
  echo "cme-dnssec-monitor/clean v0.1.0 - removes DS keys from BIND"
  echo "  usage: $ clean ${ip_addr} ${ns_server} ${domain} ${ttl} ${view}"
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

if [[ ${CME_DNSSEC_MONITOR_DEBUG:-notloaded} == "notloaded" || ${CME_DNSSEC_MONITOR_DEBUG:-notloaded} -eq 0 ]]; then
  # shellcheck disable=SC1091
  . "/etc/cme/dnssec-monitor.env"
fi

if [[ -f "${DIR}/lib.sh" ]]; then
  # shellcheck disable=SC1091
  . "${DIR}/lib.sh"
fi

declare ip_addr=$1
declare ns_server=$2
declare domain=$3
declare ttl=$4
declare view=$5

declare domain_key
declare domain_conf
declare domain_parent

# shellcheck disable=SC2086,2155
domain_parent="$(parent_domain $domain)"
domain_key="/etc/bind/rndc.${view}.key"
domain_conf="/etc/bind/rndc.${view}.conf"

log "ip_addr             : ${ip_addr}"
log "ns_server           : ${ns_server}"
log "domain_parent       : ${domain_parent}"
log "domain              : ${domain}"
log "view                : ${view}"
log "ttl                 : ${ttl}"
log "domain_key          : ${domain_key}"
log "domain_conf         : ${domain_conf}"

prepare_domain

nsupdate -k "${domain_key}" <<EOFT
server ${ns_server}
zone ${domain_parent}.
update del ${domain}. DS
send
quit
EOFT
log "...clean ${domain} DS parent records $(success_icon $?)"

nsupdate -k "${domain_key}" <<EOFT
server ${ns_server}
zone ${domain_parent}.
update del ${domain}. CDS
send
quit
EOFT
log "...clean ${domain} CDS parent records $(success_icon $?)"

nsupdate -k "${domain_key}" <<EOFT
server ${ns_server}
zone ${domain}.
update del ${domain}. DS
send
quit
EOFT
log "...clean ${domain} DS records $(success_icon $?)"

nsupdate -k "${domain_key}" <<EOFT
server ${ns_server}
zone ${domain}.
update del ${domain}. CDS
send
quit
EOFT
log "...clean ${domain} CDS records$(success_icon $?)"

rndc -c "${domain_conf}" -k "${domain_key}" -s "${ns_server}" sync -clean
log "$(success_icon $?)...syncing           : all views"

rndc -c "${domain_conf}" -k "${domain_key}" -s "${ns_server}" flush "${view}"
log "$(success_icon $?)...flushing ${view}"

# get the records
readarray -td$'\n' ds_dnskey_records < <(dig -b "${ip_addr}" "@${ns_server}" +norecurse "${domain}". DNSKEY | dnssec-dsfromkey -a SHA-384 -f - "${domain}")
readarray -td$'\n' cds_records < <(dig -b "${ip_addr}" "@${ns_server}" +short +norecurse "${domain}". CDS)
readarray -td$'\n' ds_records < <(dig -b "${ip_addr}" "@${ns_server}" +short +norecurse "${domain}". DS)

log "ds_dnskey_records:"
log "${ds_dnskey_records[*]}"
log "cds_records:"
log "${cds_records[*]}"
log "ds_records:"
log "${ds_records[*]}"
